version: '2'

networks:
  v0:
    driver: bridge
    driver_opts:
      bridge: v0
      isGateway: "true"
      ipMasq: "true"
      hairpinMode: "false"
    ipam:
      driver: default
      config:
        - subnet: "10.96.254.0/24"
          gateway: "10.96.254.254"



services:

  # a sample app with metrics enabled
  app:
    container_name: app
    build:
      context: app
    restart: always
    stop_signal: SIGKILL
    networks:
      v0:
        ipv4_address: 10.96.254.112
    ports:
      - 8080:5000
    #mem_limit: 1024m


  # the Prometheus server
  prometheus:
    container_name: prometheus
    build:
      context: prometheus
    #image: prom/prometheus:v2.2.1
    #volumes:
    #  - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      v0:
        ipv4_address: 10.96.254.111
    #mem_limit: 1024m


  # Grafana for visualization
  grafana:
    container_name: grafana
    build:
      context:  grafana 
    #image: grafana/grafana:5.1.0
    #volumes:
    #  - ./grafana/config.ini:/etc/grafana/grafana.ini
    #  - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
    #  - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    #  - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      v0:
        ipv4_address: 10.96.254.113
    #mem_limit: 1024m



