global:
  scrape_interval: 3s

  external_labels:
    monitor: "hello-world-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.254.111:9090"]

  - job_name: "hello-world"
    static_configs:
      - targets: ["192.168.254.112:5000"]
