global:
  scrape_interval: 3s

  external_labels:
    monitor: "hello-world-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "hello-world"
    static_configs:
      - targets: ["10.96.254.112:5000"]
